# Generated by Django 2.0.7 on 2018-12-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office_name', models.CharField(default='', max_length=100)),
                ('Percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
