# Generated by Django 2.0.7 on 2018-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(default='', max_length=100)),
                ('Count', models.IntegerField(default=0)),
                ('Progress', models.BooleanField(default=False)),
            ],
        ),
    ]
