# Generated by Django 2.0.7 on 2018-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
