# Generated by Django 2.0.7 on 2018-12-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181203_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='Progress',
            field=models.BooleanField(default=False),
        ),
    ]
